server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
spring:
  application:
    name: account-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb


